version: "3"
services:
  notebook:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    # Jupyter labを起動する
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: 
      /home/jovyan/work
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''